default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres123") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>

development:
  <<: *default
  database: pokemon_development

test:
  <<: *default
  database: pokemon_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    <<: *primary_production

  queue:
    <<: *primary_production

  cable:
    <<: *primary_production
