default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: liweixuan
  password: postgres123
  host: localhost
  port: 5432

development:
  <<: *default
  database: pokemon_tcg_development

test:
  <<: *default
  database: pokemon_tcg_test

production:
  <<: *default
  database: pokemon_tcg_production
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
